# This is a TOML document.


#当前使用的环境
[env]
appName="moa-demo"
appSecretKey="123"
runMode="dev"
#可以是momokeeper或者zookeeper
registryType="momokeeper" 


#registry的管理	
[registry]
	[registry.dev]
		hosts="test_moa_admin.momo.com:10020,test_moa_lookup.momo.com:10010"
	[registry.online]
		hosts="moa_admin.momo.com:10020,moa_lookup.momo.com:10010" 

#cluster的服务器
[clusters]
	[clusters.dev]
		#env=dev/online
		env="dev" 
		processTimeout=5
		#每个机器的连接数量
		poolSizePerHost = 5
		logFile="log_test.xml"
	[clusters.online]
		#env=dev/online
		env="online" 
		processTimeout=5
		#每个机器的连接数量
		poolSizePerHost = 5
		logFile="log_test.xml"

