# This is a TOML document.


#当前使用的环境
[env]
name="moa-demo"
runMode="dev"
bindAddress="172.30.3.124:13000"
#可以是momokeeper或者zookeeper
registryType="momokeeper" 

#registry的管理	
[registry]
	[registry.dev]
		hosts="test_moa_admin.momo.com:10020,test_moa_lookup.momo.com:10010"
	[registry.online]
		hosts="moa_admin.momo.com:10020,moa_lookup.momo.com:10010" 

#cluster的服务器
[clusters]
	[clusters.dev]
		#env=dev/online
		env="dev" 
		logFile="log_test.xml"
		processTimeout=5
		#最大分发处理协程数
		maxDispatcherSize=8000 
		#读取缓冲大小 
		readBufferSize=16384 
		#写入缓冲大小
		writeBufferSize=16384 
		#写异步channel长度
		writeChannelSize=1000 
		#读异步channel长度
		readChannelSize=1000 
		
	[clusters.online]
		#env=dev/online
		env="online" 
		logFile="log_test.xml"
		processTimeout=5
		#最大分发处理协程数
		maxDispatcherSize=8000 
		#读取缓冲大小 
		readBufferSize=16384
		#写入缓冲大小
		writeBufferSize=16384
		#写异步channel长度
		writeChannelSize=1000 
		#读异步channel长度
		readChannelSize=1000 
